<a href="https://colab.research.google.com/github/ezNobson/ML-AGH/blob/main/AGH_DL_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AGH_Deep Learning - NLP**
---
Autor: Michał Dyrek
---
Data: 2025-12-04
---
Data Science
---

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1) Understanding text

In [ ]:
texts = [
    "Odkryto złoża żelaza w warstwach osadowych",
    "Badania geofizyczne wskazują anomalię magnetyczną",
    "Misja kosmiczna potwierdziła obecność minerałów na Marsie",
    "Wiercenia w rejonie rud miedzi wykazały wysoką koncentrację metalu",
    "Sonda pobrała próbki gruntu z księżyca Jowisza",
    "Analiza sejsmiczna wskazuje na pęknięcia w skorupie ziemskiej"
]
print("Number of sentences", len(texts))

Number of sentences 6


Most important words:
1. żelazno, osadowych
2. badania, anomalia magnetyczna
3. misja kosmiczna, mars
4. rud miedzi, koncentracja metalu
5. sonda, księżyc Jowisza
6. Analiza sejsmiczna, skorupa ziemska

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=100)  # ograniczamy słownik do 100 najczęściej występujących słów
tokenizer.fit_on_texts(texts)          # wstaw listę tekstów
print(tokenizer.word_index)

{'w': 1, 'na': 2, 'odkryto': 3, 'złoża': 4, 'żelaza': 5, 'warstwach': 6, 'osadowych': 7, 'badania': 8, 'geofizyczne': 9, 'wskazują': 10, 'anomalię': 11, 'magnetyczną': 12, 'misja': 13, 'kosmiczna': 14, 'potwierdziła': 15, 'obecność': 16, 'minerałów': 17, 'marsie': 18, 'wiercenia': 19, 'rejonie': 20, 'rud': 21, 'miedzi': 22, 'wykazały': 23, 'wysoką': 24, 'koncentrację': 25, 'metalu': 26, 'sonda': 27, 'pobrała': 28, 'próbki': 29, 'gruntu': 30, 'z': 31, 'księżyca': 32, 'jowisza': 33, 'analiza': 34, 'sejsmiczna': 35, 'wskazuje': 36, 'pęknięcia': 37, 'skorupie': 38, 'ziemskiej': 39}


In [ ]:
sequences = tokenizer.texts_to_sequences(texts)  # wstaw listę tekstów
print(sequences)

[[3, 4, 5, 1, 6, 7], [8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 2, 18], [19, 1, 20, 21, 22, 23, 24, 25, 26], [27, 28, 29, 30, 31, 32, 33], [34, 35, 36, 2, 37, 1, 38, 39]]


In [ ]:
first_seq = sequences[0]
print(f"\nPierwsze zdanie: {texts[0]}")
print(f"Liczby: {first_seq}")


Pierwsze zdanie: Odkryto złoża żelaza w warstwach osadowych
Liczby: [3, 4, 5, 1, 6, 7]


In [ ]:
reverse_word_index = {v: k for k, v in tokenizer.word_index.items()}
decoded_words = [reverse_word_index.get(i) for i in first_seq]
print(f"Odkodowane: {decoded_words}")

Odkodowane: ['odkryto', 'złoża', 'żelaza', 'w', 'warstwach', 'osadowych']


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(sequences, padding='post')  # dopasowanie długości poprzez dodanie zer na końcu
print(padded)

[[ 3  4  5  1  6  7  0  0  0]
 [ 8  9 10 11 12  0  0  0  0]
 [13 14 15 16 17  2 18  0  0]
 [19  1 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33  0  0]
 [34 35 36  2 37  1 38 39  0]]


In [ ]:
texts = [
    "Odkryto złoża żelaza w warstwach osadowych regionu X",
    "Wiercenia w rejonie rud miedzi wykazały wysoką koncentrację metalu",
    "Misja kosmiczna potwierdziła obecność minerałów na Marsie",
    "Badania geofizyczne wykazały anomalię magnetyczną",
    "Sonda pobrała próbki gruntu z księżyca Jowisza",
    "Analiza sejsmiczna wskazuje na pęknięcia w skorupie ziemskiej"
]
labels = np.array([0, 0, 1, 1, 1, 0])  # 0 = geologia / złoża, 1 = kosmos / misje

In [ ]:
tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(texts)
sequences_train = tokenizer.texts_to_sequences(texts)

In [ ]:
padded_train = pad_sequences(sequences_train, padding='post')  # dopasowanie długości poprzez dodanie zer na końcu
print(padded)

[[ 3  4  5  1  6  7  0  0  0]
 [ 8  9 10 11 12  0  0  0  0]
 [13 14 15 16 17  2 18  0  0]
 [19  1 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33  0  0]
 [34 35 36  2 37  1 38 39  0]]


# 2) Simple model in Keras

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [ ]:
model = Sequential([
    Embedding(input_dim=100, output_dim=8, input_length=len(padded_train[0])),  # Embedding layers is to transform integer number for example 5 into list of loat nuimbers 5 -> [0.1, -0.05, 0.8, ...]
    Flatten(),
    Dense(1, activation='sigmoid')  # dla klasyfikacji binarnej
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_train, labels, epochs=10)

Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.6667 - loss: 0.6841
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6792
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6743
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.6694
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6646
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8333 - loss: 0.6597
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8333 - loss: 0.6549
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6501
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6452
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.6404


In [ ]:
test_text = ["Nowe badania wskazują złoża niklu na asteroidzie"]
seq = tokenizer.texts_to_sequences(test_text)
padded_test = pad_sequences(seq, maxlen=len(padded_train[0]), padding='post')

In [ ]:
prediction = model.predict(padded_test)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0.52215403]], dtype=float32)

In [ ]:
print(f"Prediction results: {prediction[0][0]:.4f}")

Prediction results: 0.5222


In [ ]:
if prediction < 0.5:
    print("Geology")
else:
    print("Cosmos")

Cosmos


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

In [ ]:
def tokenize_pad(X):
    seq = tokenizer.texts_to_sequences(X)
    return pad_sequences(seq, maxlen=len(padded_train[0]), padding='post')

In [ ]:
pipeline = Pipeline([
    ('tokenize_pad', FunctionTransformer(tokenize_pad, validate=False)),
    ('model', model)
])

In [ ]:
new_texts = ["Eksploracja Marsa wykazała obecność żelaza i niklu"]

In [ ]:
prediction = pipeline.predict(new_texts)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step


/usr/local/lib/python3.12/dist-packages/sklearn/pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(


array([[0.52461106]], dtype=float32)

In [ ]:
if prediction[0][0] > 0.5:
  print("Cosmos")
else:
  print("Geology")

Cosmos


# 3) Addidtional cleaning function

In [ ]:
def clean_fun(text_list):
  cleaned =[]
  stop_words = ["w", "i", "na", "z"]
  for text in text_list:
    text = text.lower()
    for stop_word in stop_words:
      text = text.replace(stop_word, "")
    cleaned.append(text)
  return cleaned

In [ ]:
pipeline_stop_words = Pipeline([
    ('clean', FunctionTransformer(clean_fun, validate=False)),
    ('tokenize_pad', FunctionTransformer(tokenize_pad, validate=False)),
    ('model', model)
])